name: Docker Build & Publish

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  check:
    name: Validate Code
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '18'
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: classes

  update_repository:
    name: Update repository
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '18'
      - run: rm -rf .git/ # delete .git here to ignore the parent git repo and only care about plugin-repo
      - uses: actions/checkout@v2
        with:
          ref: plugin-repo
          path: ci-repo
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: buildRepository
      - run: |
          cd ci-repo
          git config --local user.email "actions@github.com"
          git config --local user.name "actions-user"
          git add .
          git commit -m "Update plugin repository"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: plugin-repo
          directory: ci-repo